GET http://localhost:8080/weather/moscow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZUBtYWlsLmNvbSIsInNjb3BlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwiaXNzIjoib25saW5lLXJhZGlvIiwiaWF0IjoxNjUzOTE2MjUwLCJleHAiOjE2NTQ3ODAyNTB9.qEx0w0QR-WMWVdogxKY02dVM5gSsq2OVwoERaps_98w

###
POST http://localhost:8080/signup
Content-Type: application/json

{
  "nickname": "username",
  "email": "username@mail.com",
  "password": "qwerty007"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "username@mail.com",
  "password": "qwerty007"
}

###
GET http://localhost:8080/status
Content-Type: application/json

###
GET https://api.openweathermap.org/data/2.5/weather?q=moscow&appid=d64cde12deca23990a6e956bf65b16aa