GET http://localhost:8080/weather/moscow
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZUBtYWlsLmNvbSIsInNjb3BlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwiaXNzIjoib25saW5lLXJhZGlvIiwiaWF0IjoxNjUzOTkyODQ3LCJleHAiOjE2NTQ4NTY4NDd9.ogLjFdWpfJoJ-5TT_V9lSPm45G7y_RIo5G-SHlUWQcM

###

GET http://localhost:8080/src/main/resources/swagger-ui.html

###
POST http://localhost:8080/signup
Content-Type: application/json

{
  "nickname": "username",
  "email": "username@mail.com",
  "password": "qwerty007"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "username@mail.com",
  "password": "qwerty007"
}

###
GET http://localhost:8080/status
Content-Type: application/json

###
GET https://api.openweathermap.org/data/2.5/weather?q=moscow&appid=d64cde12deca23990a6e956bf65b16aa

### Like song
POST http://localhost:8080/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZUBtYWlsLmNvbSIsInNjb3BlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwiaXNzIjoib25saW5lLXJhZGlvIiwiaWF0IjoxNjUzOTkzMjUzLCJleHAiOjE2NTQ4NTcyNTN9.9XBNyc9Ea6G_T5yO3NzJLdFmaIq4yUmFNjGiBzQbuW4
Content-Type: application/json

{
  "email": "username@mail.com",
  "songId": 8
}

###
GET http://localhost:8080/songs/top/breaks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZUBtYWlsLmNvbSIsInNjb3BlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwiaXNzIjoib25saW5lLXJhZGlvIiwiaWF0IjoxNjU0MDY3NDIzLCJleHAiOjE2NTQ5MzE0MjN9.1-v0n4NBGhNMME-vTLZCZwFAVH-H4DmJvmzdO66O8NI

###
GET http://localhost:8080/leaderboard
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZUBtYWlsLmNvbSIsInNjb3BlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwiaXNzIjoib25saW5lLXJhZGlvIiwiaWF0IjoxNjU0MDY3NDIzLCJleHAiOjE2NTQ5MzE0MjN9.1-v0n4NBGhNMME-vTLZCZwFAVH-H4DmJvmzdO66O8NI

###
GET http://localhost:8080/profile/username
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VybmFtZUBtYWlsLmNvbSIsInNjb3BlcyI6W3siYXV0aG9yaXR5IjoiVVNFUiJ9XSwiaXNzIjoib25saW5lLXJhZGlvIiwiaWF0IjoxNjU0MDY3NDIzLCJleHAiOjE2NTQ5MzE0MjN9.1-v0n4NBGhNMME-vTLZCZwFAVH-H4DmJvmzdO66O8NI
