GET http://localhost:8080/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQG1haWwuY29tIiwic2NvcGVzIjpbeyJhdXRob3JpdHkiOiJVU0VSIn1dLCJpc3MiOiJvbmxpbmUtcmFkaW8iLCJpYXQiOjE2NTMyMzE1OTksImV4cCI6MTY1NDA5NTU5OX0.BJJmWlcxadlehc3GKRWGiONuN_4Lpru8RwN46nG7qnk

###
POST http://localhost:8080/signup
Content-Type: application/json

{
  "nickname": "u",
  "email": "usernamm",
  "password": "q"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "username@mail.com",
  "password": "qwerty"
}

###
GET http://localhost:8080/status
Content-Type: application/json

###
GET https://api.openweathermap.org/data/2.5/weather?q=moscow&appid=d64cde12deca23990a6e956bf65b16aa